server:
  port: 8041
  base-path: /communication-integration-template
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://172.19.41.8:5432/evamdb
    username: evam
    password: evam123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #oracle org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      jdbc:
        batch_size: 50
        order_inserts: false



logging:
  config: config/log4j2.xml

kafka:
  bootstrap-address: vmkafkauat01.westeastbank.com:9092
  communication-uuid-check: true #If changed to false, the communicationUUID index should be removed. If it is not removed, it may be saved in the push status table incompletely.
  event-topic:
    name: campaignEventsTopic
    partition: 8
    replication: 1
    retention-ms: 43200000
  integration-topic:
    name: customPushTopic
    group: customPushCommunicationGroup
    auto-offset-reset: earliest
    enable-auto-commit: false
    partition: 8
    replication: 1
    retention-ms: 43200000
    concurrency: 4
    max-pool-records: 1000
    #custom-config-properties:
    #  - key: "heartbeat.interval.ms"
    #    value: "3000"
  producer:
    buffer-memory: 33554432
    batch-size: 16384
    linger-ms: 300
    acks: 1
    #custom-config-properties:
    #  - key: "compression.type"
    #    value: "none"

##Push notification api inform

push-config:
  API_URL: https://tbi-apim-dev.azure-api.net/mobileservice/api/v3/sendPushNotification
  API_VERSION: v3
  CONTENT_TYPE: application/json
  ACCEPT_TYPE: application/json
  OCP_APIM_SUBSCRIPTION_KEY: 21d69f5f698f430eaa64796d9407a5ff
  OCP_APIM_TRACE: true

search-customer-config:
  API_URL: https://tbi-apim.azure-api.net/ecomm2/searchCustomer
  OCP_APIM_TRACE: true
  OCP_APIM_SUBSCRIPTION_KEY: 1f0a04a6ad7a4dac80c664706fdcb93c
    ##search customer configuration


### RATE LIMITER
#### The client send method is called a maximum of 5 times in 1 second.

#resilience4j.ratelimiter:
#  instances:
#    client-limiter:
#      limitForPeriod: 5
#      limitRefreshPeriod: 1s
