server:
  port: 8041
  base-path: /communication-integration-template
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://10.101.197.21:5432/evam
    username: evam
    password: evam123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #oracle org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 50
        order_inserts: false



logging:
  config: config/log4j2.xml

kafka:
  bootstrap-address: 10.101.197.31:9092,10.101.197.32:9092
  communication-uuid-check: true #If changed to false, the communicationUUID index should be removed. If it is not removed, it may be saved in the push status table incompletely.
  event-topic:
    name: campaignEventsTopic
    partition: 8
    replication: 1
    retention-ms: 43200000
  integration-topic:
    name: customPushTopic
    group: customPushCommunicationGroup
    auto-offset-reset: earliest
    enable-auto-commit: false
    partition: 8
    replication: 1
    retention-ms: 43200000
    concurrency: 4
    max-pool-records: 1000
    #custom-config-properties:
    #  - key: "heartbeat.interval.ms"
    #    value: "3000"
  producer:
    buffer-memory: 33554432
    batch-size: 16384
    linger-ms: 300
    acks: 1
    #custom-config-properties:
    #  - key: "compression.type"
    #    value: "none"

##Push notification api inform

push-config:
  API_URL: https://tbi-apim-prd.azure-api.net/mobileservice/api/sendPushNotification
  API_VERSION: v1
  CONTENT_TYPE: application/json
  ACCEPT_TYPE: application/json
 #TIMEOUT_MILLIS: 10000
  OCP_APIM_SUBSCRIPTION_KEY: ee6998a8d80646baaaa98e13d7405a07
  OCP_APIM_TRACE: true

search-customer-config:
  API_URL: https://tbi-apim-prd.azure-api.net/ecombg/searchCustomer
  OCP_APIM_TRACE: true
  OCP_APIM_SUBSCRIPTION_KEY: ee6998a8d80646baaaa98e13d7405a07
    ##search customer configuration


### RATE LIMITER
#### The client send method is called a maximum of 5 times in 1 second.

resilience4j.ratelimiter:
  instances:
   client-limiter:
     limitForPeriod: 5
     limitRefreshPeriod: 1s
