server:
  port: 8042
  base-path: /communication-integration-template
  error:
    include-message: always

spring:
  datasource:
    url: 
    username: 
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect #oracle org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 50
        order_inserts: false


logging:
  config: config/log4j2.xml
##Push notification api inform

rpa-speedy-config:
  API_URL: 
  CACHE_CONTROL: no-cache
  CONTENT_TYPE: application/json;charset=UTF-8
  ACCEPT_TYPE: application/json
  TIMEOUT_MILLIS: 10000
  OCP_APIM_SUBSCRIPTION_KEY: 

