CREATE SEQUENCE IF NOT EXISTS INT_RESOURCE_TEMPLATE_SEQ;

CREATE TABLE IF NOT EXISTS INT_RESOURCE_TEMPLATE
(
    ID                 BIGINT PRIMARY KEY DEFAULT NEXTVAL('INT_RESOURCE_TEMPLATE_SEQ'),
    COMMUNICATION_CODE VARCHAR(255),
    CONTENT            TEXT,
    SCENARIO_NAME      VARCHAR(255),
    SCENARIO_VERSION   INT,
    UNIQUE (COMMUNICATION_CODE, SCENARIO_NAME, SCENARIO_VERSION)
);

CREATE SEQUENCE IF NOT EXISTS INT_CUSTOM_COMM_STATUS_SEQ;

CREATE TABLE IF NOT EXISTS INT_CUSTOM_COMM_STATUS
(
    ID                 BIGINT PRIMARY KEY DEFAULT NEXTVAL('INT_CUSTOM_COMM_STATUS_SEQ'),
    COMMUNICATION_UUID VARCHAR(50)
        CONSTRAINT INT_CUSTOM_COMM_STATUS_UUID_ID UNIQUE,
    PROVIDER           VARCHAR(50),
    PROVIDER_RESULT_ID VARCHAR(250),
    REASON             VARCHAR(250),
    STATUS             VARCHAR(50),
    STATUS_UPDATE_TIME timestamp
);